services:
  # MongoDB Database
  - type: web
    name: get-to-know-mongodb
    env: docker
    dockerfilePath: ./Dockerfile.mongodb
    plan: free
    envVars:
      - key: MONGO_INITDB_ROOT_USERNAME
        sync: false
      - key: MONGO_INITDB_ROOT_PASSWORD
        sync: false

  # Go Backend API
  - type: web
    name: get-to-know-backend
    env: docker
    dockerfilePath: ./src/backend/get-to-know-game-go/Dockerfile
    plan: free
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 5012
      - key: FIBER_ENV
        value: production
    healthCheckPath: /health

  # SvelteKit Frontend
  - type: web
    name: get-to-know-frontend
    env: docker
    dockerfilePath: ./src/frontend/get-to-know-game/Dockerfile
    plan: free
    envVars:
      - key: VITE_API_URL
        sync: false
