version: '3.8'

services:
  frontend:
    build:
      context: ../src/frontend/get-to-know-game
      dockerfile: Dockerfile.oracle
    restart: unless-stopped
    expose:
      - "3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://api.pairglow.com

  backend:
    build:
      context: ../src/backend/get-to-know-game-go
      dockerfile: Dockerfile.oracle
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DATABASE_NAME=GetToKnowGame
      - PORT=8080
      - GIN_MODE=release
    expose:
      - "8080"

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-ssl.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - frontend
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done;'"
